### ISSUE TITLE
What should mock be used for

### ISSUE THREAD

**Issue by akegalj** [advancedtelematic/quickcheck-state-machine#236]
I am not sure what should be `mock` , last parammeter to `StateMachine` be used for and how it is used in a current implementation?

This line is onpar with my understanding https://github.com/advancedtelematic/quickcheck-state-machine/blob/master/test/Echo.hs#L146

Also I can't deduce why `mock` would be needed from readme section on hackage:
```
Sequential property
The sequential property checks if the model is consistent with respect to the semantics. The way this is done is:

generate a list of actions;

starting from the initial model, for each action do the the following:

check that the pre-condition holds;
if so, execute the action using the semantics;
check if the the post-condition holds;
advance the model using the transition function.
If something goes wrong, shrink the initial list of actions and present a minimal counterexample.

Parallel property
The parallel property checks if parallel execution of the semantics can be explained in terms of the sequential model. This is useful for trying to find race conditions -- which normally can be tricky to test for. It works as follows:

generate a list of actions that will act as a sequential prefix for the parallel program (think of this as an initialisation bit that setups up some state);

generate two lists of actions that will act as parallel suffixes;

execute the prefix sequentially;

execute the suffixes in parallel and gather the a trace (or history) of invocations and responses of each action;

try to find a possible sequential interleaving of action invocations and responses that respects the post-conditions.

The last step basically tries to find a linearisation of calls that could have happend on a single thread.
```

**Comment by stevana** [comment]
The way `mock` should be used is that it should return a mocked response to each
command using values from the model, e.g. `Read` from the README looks up the
value associated to the reference we are trying to read from in the model. If a
command returns `Reference`s, e.g. `Create` from the README, then `genSym`
should be used to create those (`Symbolic`) `Reference`s.

Why `mock` is needed is more complicated.

Most importantly, is that it solves the problem of allowing more than one
`Reference` in a response. It's a hack however and I wish I could find a better
solution.

Another reason for not removing it is, because I've also played around with the
idea of using `mock` to create a mocked APIs. I've still not worked out the
details of how exactly this should work though. (Because this isn't actually
used by the library yet, it's not important for `mock` to return the correct
responses, e.g. having `mock` for `Read` return `ReadValue 0` is completely
fine.)

Does that make sense?

I'll update the README to include more info about `mock` while I keep thinking
of how to get rid of it or actually use it for something meaningful...

**Comment by stevana** [comment]
> but it produced correct output (test passed) in both cases. That's when I figured my understanding about this feature is still vauge but I see it is still WIP

When I said:

> (Because this isn't actually
used by the library yet, it's not important for mock to return the correct
responses, e.g. having mock for Read return ReadValue 0 is completely
fine.)

I should have added that the only important part is that `Reference` responses are generated by `genSym`s, because that is what increases the state counter that you mentioned in the beginning which is used for generating commands...

I'll make sure to mention both these things when I update the README!

Regarding how to `mock` more complex systems: we can't really answer this question until we actually know how to use `mock` for mocking APIs and how we intend to use those mocked APIs...

Perhaps only happy path is enough? Perhaps there should be fault injection commands which steer the unhappy paths? I don't know yet... But for now, while `mock` is only used for `genSym`ing references, it doesn't really matter.

If you have any ideas on the topic, I'm all ears, :-).

**Comment by akegalj** [comment]
Thanks for prompt replays.

I will have to dive deeper into implementation details to capture full understanding of underlying mechanics. There is also mention of few papers in README that I'll have to read to get a full picture (hopefully by end of the year!). Will give my feadback eventually (based on our use case)

**Comment by stevana** [comment]
Feel free to ask questions or open further issues if there's something you'd like explained better in the documentation! I'm happy to explain things further, especially during working hours :-).

Also, I'm looking forward to hear your feedback!
